require('dotenv').config({ path: '../../.env' });
const mongoose = require('mongoose');
const AIModel = require('../models/AIModel');

const MONGO_URI = process.env.MONGO_URI || 'mongodb://localhost:27017/nexusai-db';

/** Rich dummy catalogue for marketplace — all fields match AIModel schema */
const models = [
  { slug: 'gpt-4o', name: 'GPT-4o', provider: 'OpenAI', providerColor: '#10a37f', categories: ['Text Generation', 'Multimodal', 'Code', 'Reasoning', 'Chat'], description: "OpenAI's flagship multimodal model with native vision, audio, and text. Delivers GPT-4 intelligence at faster speeds with improved instruction following.", contextWindow: 128000, pricing: { input: 2.5, output: 10.0, unit: 'per 1M tokens', tier: 'mid' }, strengths: ['Exceptional multimodal understanding', 'Fast response times', 'Strong instruction following'], limitations: ['Knowledge cutoff may lag', 'API costs at scale'], scores: { reasoning: 95, coding: 90, creativity: 88, speed: 85, multimodal: 97, contextHandling: 90, costEfficiency: 72 }, releaseDate: '2024-05', openSource: false, apiAvailable: true },
  { slug: 'gpt-4-turbo', name: 'GPT-4 Turbo', provider: 'OpenAI', providerColor: '#10a37f', categories: ['Text Generation', 'Reasoning', 'Code', 'Chat'], description: 'High-capability GPT-4 variant with 128K context, vision support, and deep reasoning for complex tasks.', contextWindow: 128000, pricing: { input: 10.0, output: 30.0, unit: 'per 1M tokens', tier: 'premium' }, strengths: ['Deep reasoning chains', 'Vision capabilities', '128K context window'], limitations: ['Higher pricing vs newer models', 'Slower than GPT-4o'], scores: { reasoning: 93, coding: 88, creativity: 85, speed: 68, multimodal: 80, contextHandling: 90, costEfficiency: 50 }, releaseDate: '2024-01', openSource: false, apiAvailable: true },
  { slug: 'gpt-3-5-turbo', name: 'GPT-3.5 Turbo', provider: 'OpenAI', providerColor: '#10a37f', categories: ['Text Generation', 'Chat', 'Code'], description: 'Fast, affordable conversational AI ideal for high-volume apps where cost efficiency matters more than frontier performance.', contextWindow: 16385, pricing: { input: 0.5, output: 1.5, unit: 'per 1M tokens', tier: 'budget' }, strengths: ['Very low cost', 'Fast inference', 'Stable API'], limitations: ['Weaker reasoning vs GPT-4', 'No vision'], scores: { reasoning: 68, coding: 70, creativity: 65, speed: 95, multimodal: 0, contextHandling: 55, costEfficiency: 95 }, releaseDate: '2023-03', openSource: false, apiAvailable: true },
  { slug: 'gpt-4o-mini', name: 'GPT-4o Mini', provider: 'OpenAI', providerColor: '#10a37f', categories: ['Text Generation', 'Chat', 'Code', 'Speed'], description: "OpenAI's affordable multimodal model outperforming GPT-3.5 on most benchmarks at a fraction of the cost.", contextWindow: 128000, pricing: { input: 0.15, output: 0.6, unit: 'per 1M tokens', tier: 'budget' }, strengths: ['Very affordable', 'Multimodal capable', '128K context'], limitations: ['Less capable than GPT-4o'], scores: { reasoning: 78, coding: 80, creativity: 74, speed: 92, multimodal: 82, contextHandling: 88, costEfficiency: 93 }, releaseDate: '2024-07', openSource: false, apiAvailable: true },
  { slug: 'o1-preview', name: 'o1-preview', provider: 'OpenAI', providerColor: '#10a37f', categories: ['Reasoning', 'Code', 'Research', 'Math'], description: 'Reasoning model trained with reinforcement learning for complex STEM and multi-step planning tasks.', contextWindow: 128000, pricing: { input: 15.0, output: 60.0, unit: 'per 1M tokens', tier: 'premium' }, strengths: ['Exceptional chain-of-thought', 'Math & code competitions'], limitations: ['Higher latency', 'Premium pricing'], scores: { reasoning: 99, coding: 96, creativity: 82, speed: 55, multimodal: 40, contextHandling: 88, costEfficiency: 35 }, releaseDate: '2024-09', openSource: false, apiAvailable: true },
  { slug: 'claude-3-5-sonnet', name: 'Claude 3.5 Sonnet', provider: 'Anthropic', providerColor: '#d4794a', categories: ['Text Generation', 'Reasoning', 'Code', 'Chat', 'Analysis'], description: "Anthropic's most intelligent model with frontier reasoning, best-in-class coding, and 200K context window.", contextWindow: 200000, pricing: { input: 3.0, output: 15.0, unit: 'per 1M tokens', tier: 'mid' }, strengths: ['Top-tier coding benchmarks', '200K context', 'Constitutional AI safety'], limitations: ['No image generation', 'Higher output cost'], scores: { reasoning: 97, coding: 98, creativity: 90, speed: 78, multimodal: 75, contextHandling: 98, costEfficiency: 68 }, releaseDate: '2024-10', openSource: false, apiAvailable: true },
  { slug: 'claude-3-opus', name: 'Claude 3 Opus', provider: 'Anthropic', providerColor: '#d4794a', categories: ['Text Generation', 'Reasoning', 'Research', 'Analysis'], description: "Anthropic's most powerful model for highly complex reasoning, nuanced content, and deep comprehension.", contextWindow: 200000, pricing: { input: 15.0, output: 75.0, unit: 'per 1M tokens', tier: 'premium' }, strengths: ['Graduate-level reasoning', 'Nuanced long-form writing'], limitations: ['Most expensive Claude model', 'Slower'], scores: { reasoning: 99, coding: 88, creativity: 95, speed: 55, multimodal: 72, contextHandling: 98, costEfficiency: 30 }, releaseDate: '2024-03', openSource: false, apiAvailable: true },
  { slug: 'claude-3-haiku', name: 'Claude 3 Haiku', provider: 'Anthropic', providerColor: '#d4794a', categories: ['Text Generation', 'Chat', 'Code', 'Speed'], description: "Anthropic's fastest compact model for near-instant responsiveness and cost-sensitive production applications.", contextWindow: 200000, pricing: { input: 0.25, output: 1.25, unit: 'per 1M tokens', tier: 'budget' }, strengths: ['Extremely fast', 'Very affordable', '200K context'], limitations: ['Weaker advanced coding'], scores: { reasoning: 72, coding: 74, creativity: 68, speed: 98, multimodal: 70, contextHandling: 90, costEfficiency: 97 }, releaseDate: '2024-03', openSource: false, apiAvailable: true },
  { slug: 'claude-3-5-haiku', name: 'Claude 3.5 Haiku', provider: 'Anthropic', providerColor: '#d4794a', categories: ['Text Generation', 'Chat', 'Speed', 'Vision'], description: 'Fast Haiku-class model with improved reasoning and vision at a fraction of Sonnet cost.', contextWindow: 200000, pricing: { input: 1.0, output: 5.0, unit: 'per 1M tokens', tier: 'budget' }, strengths: ['Vision + speed', 'Great for prod scale'], limitations: ['Below Sonnet on hardest tasks'], scores: { reasoning: 82, coding: 80, creativity: 74, speed: 94, multimodal: 78, contextHandling: 92, costEfficiency: 90 }, releaseDate: '2024-11', openSource: false, apiAvailable: true },
  { slug: 'gemini-1-5-pro', name: 'Gemini 1.5 Pro', provider: 'Google', providerColor: '#4285f4', categories: ['Text Generation', 'Multimodal', 'Code', 'Reasoning', 'Research'], description: "Google's most capable model with 1M token context, native video understanding, and cross-modal reasoning.", contextWindow: 1000000, pricing: { input: 3.5, output: 10.5, unit: 'per 1M tokens', tier: 'mid' }, strengths: ['1M token context', 'Native video understanding'], limitations: ['Can be slower on very long contexts'], scores: { reasoning: 92, coding: 85, creativity: 84, speed: 75, multimodal: 95, contextHandling: 100, costEfficiency: 70 }, releaseDate: '2024-05', openSource: false, apiAvailable: true },
  { slug: 'gemini-1-5-flash', name: 'Gemini 1.5 Flash', provider: 'Google', providerColor: '#4285f4', categories: ['Text Generation', 'Multimodal', 'Chat', 'Speed'], description: "Google's fast, cost-efficient multimodal model with 1M context at a fraction of Pro's cost.", contextWindow: 1000000, pricing: { input: 0.075, output: 0.3, unit: 'per 1M tokens', tier: 'budget' }, strengths: ['Extremely cost-efficient', '1M context'], limitations: ['Weaker complex reasoning'], scores: { reasoning: 78, coding: 75, creativity: 72, speed: 93, multimodal: 85, contextHandling: 100, costEfficiency: 98 }, releaseDate: '2024-05', openSource: false, apiAvailable: true },
  { slug: 'gemini-2-flash', name: 'Gemini 2.0 Flash', provider: 'Google DeepMind', providerColor: '#4285f4', categories: ['Text Generation', 'Multimodal', 'Code', 'Reasoning'], description: 'Next-gen Flash with improved reasoning, faster throughput, and stronger tool use for agents.', contextWindow: 1000000, pricing: { input: 0.1, output: 0.4, unit: 'per 1M tokens', tier: 'budget' }, strengths: ['Agentic tool use', 'Low latency'], limitations: ['Not full Pro-tier depth'], scores: { reasoning: 88, coding: 86, creativity: 82, speed: 94, multimodal: 92, contextHandling: 98, costEfficiency: 96 }, releaseDate: '2024-12', openSource: false, apiAvailable: true },
  { slug: 'gemini-2-pro', name: 'Gemini 2.0 Pro', provider: 'Google DeepMind', providerColor: '#4285f4', categories: ['Text Generation', 'Multimodal', 'Reasoning', 'Research'], description: 'Frontier Gemini tier for long documents, video reasoning, and enterprise analytics workloads.', contextWindow: 2000000, pricing: { input: 7.0, output: 21.0, unit: 'per 1M tokens', tier: 'premium' }, strengths: ['2M context window class', 'Expert multimodal'], limitations: ['Premium pricing'], scores: { reasoning: 96, coding: 90, creativity: 88, speed: 70, multimodal: 98, contextHandling: 100, costEfficiency: 45 }, releaseDate: '2024-12', openSource: false, apiAvailable: true },
  { slug: 'gemini-ultra', name: 'Gemini Ultra', provider: 'Google', providerColor: '#4285f4', categories: ['Text Generation', 'Multimodal', 'Reasoning', 'Research'], description: "Google's most powerful model achieving SOTA on MMLU benchmarks for expert-level multimodal tasks.", contextWindow: 32000, pricing: { input: 20.0, output: 60.0, unit: 'per 1M tokens', tier: 'premium' }, strengths: ['MMLU benchmark leader', 'Scientific problem solving'], limitations: ['Very expensive', 'Smaller context than Pro'], scores: { reasoning: 96, coding: 87, creativity: 86, speed: 60, multimodal: 96, contextHandling: 70, costEfficiency: 25 }, releaseDate: '2024-02', openSource: false, apiAvailable: true },
  { slug: 'llama-4-maverick', name: 'Llama 4 Maverick', provider: 'Meta', providerColor: '#0668e1', categories: ['Text Generation', 'Multimodal', 'Reasoning', 'Open Source'], description: '400B+ MoE flagship with strong agentic behaviour, multimodal IO, and open weights for research.', contextWindow: 128000, pricing: { input: 2.0, output: 2.0, unit: 'per 1M tokens (hosted)', tier: 'mid' }, strengths: ['Open weights', 'MoE efficiency', 'Multimodal'], limitations: ['Heavy compute to self-host'], scores: { reasoning: 91, coding: 88, creativity: 85, speed: 72, multimodal: 88, contextHandling: 90, costEfficiency: 78 }, releaseDate: '2025-04', openSource: true, apiAvailable: true },
  { slug: 'llama-3-1-405b', name: 'Llama 3.1 405B', provider: 'Meta', providerColor: '#0668e1', categories: ['Text Generation', 'Reasoning', 'Code', 'Research'], description: "Meta's largest open-source model matching GPT-4 benchmarks with fully open weights for on-premise deployment.", contextWindow: 128000, pricing: { input: 3.0, output: 3.0, unit: 'per 1M tokens (hosted)', tier: 'mid' }, strengths: ['Open source / self-hostable', 'Competitive with GPT-4'], limitations: ['High compute for self-hosting'], scores: { reasoning: 89, coding: 86, creativity: 82, speed: 60, multimodal: 40, contextHandling: 88, costEfficiency: 80 }, releaseDate: '2024-07', openSource: true, apiAvailable: true },
  { slug: 'llama-3-1-70b', name: 'Llama 3.1 70B', provider: 'Meta', providerColor: '#0668e1', categories: ['Text Generation', 'Code', 'Chat', 'Reasoning'], description: "Meta's mid-size open model balancing capability, efficiency, and strong multilingual support.", contextWindow: 128000, pricing: { input: 0.59, output: 0.79, unit: 'per 1M tokens (hosted)', tier: 'budget' }, strengths: ['Open source', 'Cost-effective at scale'], limitations: ['Weaker than 405B on complex tasks'], scores: { reasoning: 80, coding: 78, creativity: 75, speed: 78, multimodal: 0, contextHandling: 85, costEfficiency: 90 }, releaseDate: '2024-07', openSource: true, apiAvailable: true },
  { slug: 'mistral-large-2', name: 'Mistral Large 2', provider: 'Mistral AI', providerColor: '#ff6b35', categories: ['Text Generation', 'Reasoning', 'Code', 'Multilingual'], description: 'Frontier Mistral model with improved reasoning, JSON mode, and strong EU deployment story.', contextWindow: 128000, pricing: { input: 2.0, output: 6.0, unit: 'per 1M tokens', tier: 'mid' }, strengths: ['Multilingual', 'Function calling', 'GDPR-friendly'], limitations: ['Smaller ecosystem than OpenAI'], scores: { reasoning: 88, coding: 86, creativity: 80, speed: 82, multimodal: 0, contextHandling: 88, costEfficiency: 76 }, releaseDate: '2024-07', openSource: false, apiAvailable: true },
  { slug: 'mistral-large', name: 'Mistral Large', provider: 'Mistral AI', providerColor: '#ff6b35', categories: ['Text Generation', 'Reasoning', 'Code', 'Multilingual'], description: "Mistral AI's flagship model with native function calling and excellent French/German/Spanish support.", contextWindow: 128000, pricing: { input: 3.0, output: 9.0, unit: 'per 1M tokens', tier: 'mid' }, strengths: ['Strong multilingual support', 'Native function calling'], limitations: ['No native image understanding'], scores: { reasoning: 85, coding: 82, creativity: 78, speed: 80, multimodal: 0, contextHandling: 85, costEfficiency: 75 }, releaseDate: '2024-02', openSource: false, apiAvailable: true },
  { slug: 'codestral', name: 'Codestral', provider: 'Mistral AI', providerColor: '#ff6b35', categories: ['Code', 'Text Generation', 'Chat'], description: 'Specialised coding model with fill-in-the-middle support and strong HumanEval scores.', contextWindow: 32000, pricing: { input: 0.3, output: 0.9, unit: 'per 1M tokens', tier: 'budget' }, strengths: ['Code completion', 'Low cost'], limitations: ['Narrower than general models'], scores: { reasoning: 72, coding: 92, creativity: 65, speed: 90, multimodal: 0, contextHandling: 70, costEfficiency: 94 }, releaseDate: '2024-05', openSource: false, apiAvailable: true },
  { slug: 'mixtral-8x22b', name: 'Mixtral 8x22B', provider: 'Mistral AI', providerColor: '#ff6b35', categories: ['Text Generation', 'Code', 'Open Source', 'Reasoning'], description: 'Sparse MoE model combining efficiency with strong open-weight performance.', contextWindow: 65536, pricing: { input: 1.2, output: 1.2, unit: 'per 1M tokens (hosted)', tier: 'budget' }, strengths: ['MoE efficiency', 'Good quality/cost'], limitations: ['Not latest frontier'], scores: { reasoning: 84, coding: 82, creativity: 78, speed: 85, multimodal: 0, contextHandling: 82, costEfficiency: 88 }, releaseDate: '2024-04', openSource: true, apiAvailable: true },
  { slug: 'dalle-3', name: 'DALL·E 3', provider: 'OpenAI', providerColor: '#10a37f', categories: ['Image Generation', 'Creative', 'Multimodal'], description: "OpenAI's SOTA image generation model with exceptional prompt adherence and photorealistic outputs.", contextWindow: null, pricing: { input: 0.04, unit: 'per image (1024×1024)', tier: 'mid' }, strengths: ['Prompt adherence', 'Photorealistic outputs'], limitations: ['Per-image pricing'], scores: { reasoning: 0, coding: 0, creativity: 93, speed: 72, multimodal: 95, contextHandling: 0, costEfficiency: 65 }, releaseDate: '2023-10', openSource: false, apiAvailable: true },
  { slug: 'stable-diffusion-xl', name: 'Stable Diffusion XL', provider: 'Stability AI', providerColor: '#7c3aed', categories: ['Image Generation', 'Creative', 'Open Source'], description: "Stability AI's open-source image model for local deployment with full customization and no per-image costs.", contextWindow: null, pricing: { input: 0.0, unit: 'free (self-hosted)', tier: 'free' }, strengths: ['Fully open source', 'Local deployment'], limitations: ['Requires GPU'], scores: { reasoning: 0, coding: 0, creativity: 88, speed: 65, multimodal: 90, contextHandling: 0, costEfficiency: 100 }, releaseDate: '2023-07', openSource: true, apiAvailable: true },
  { slug: 'midjourney-v6', name: 'Midjourney V6', provider: 'Midjourney', providerColor: '#e63946', categories: ['Image Generation', 'Creative', 'Art'], description: "Midjourney's flagship artistic model with unmatched aesthetics for cinematic and concept art generation.", contextWindow: null, pricing: { input: 10.0, unit: 'per month (basic plan)', tier: 'mid' }, strengths: ['Unmatched artistic quality', 'Cinematic outputs'], limitations: ['Discord-based interface', 'No public API'], scores: { reasoning: 0, coding: 0, creativity: 98, speed: 68, multimodal: 88, contextHandling: 0, costEfficiency: 60 }, releaseDate: '2024-01', openSource: false, apiAvailable: false },
  { slug: 'whisper', name: 'Whisper V3', provider: 'OpenAI', providerColor: '#10a37f', categories: ['Audio', 'Speech-to-Text', 'Transcription', 'Translation'], description: "OpenAI's speech recognition model trained on 680K hours of audio, supporting 99 languages with near-human accuracy.", contextWindow: null, pricing: { input: 0.006, unit: 'per minute of audio', tier: 'budget' }, strengths: ['99-language support', 'Near-human accuracy'], limitations: ['No speaker diarization'], scores: { reasoning: 0, coding: 0, creativity: 30, speed: 78, multimodal: 80, contextHandling: 0, costEfficiency: 95 }, releaseDate: '2022-09', openSource: true, apiAvailable: true },
  { slug: 'elevenlabs-turbo', name: 'Eleven Turbo v2', provider: 'ElevenLabs', providerColor: '#000000', categories: ['Audio', 'Text-to-Speech', 'Voice'], description: 'Low-latency TTS with expressive voices for real-time apps, games, and assistants.', contextWindow: null, pricing: { input: 0.18, unit: 'per 1K characters', tier: 'mid' }, strengths: ['Expressive voices', 'Streaming'], limitations: ['Character-based pricing'], scores: { reasoning: 0, coding: 0, creativity: 85, speed: 92, multimodal: 75, contextHandling: 0, costEfficiency: 70 }, releaseDate: '2024-03', openSource: false, apiAvailable: true },
  { slug: 'suno-v3', name: 'Suno v3', provider: 'Suno', providerColor: '#f59e0b', categories: ['Audio', 'Music Generation', 'Creative'], description: 'Generates full songs with lyrics and instrumentation from text prompts.', contextWindow: null, pricing: { input: 10.0, unit: 'per month (pro)', tier: 'mid' }, strengths: ['Full tracks', 'Lyrics + instrumentation'], limitations: ['Subscription model'], scores: { reasoning: 0, coding: 0, creativity: 96, speed: 70, multimodal: 70, contextHandling: 0, costEfficiency: 55 }, releaseDate: '2024-03', openSource: false, apiAvailable: true },
  { slug: 'gemma-2', name: 'Gemma 2', provider: 'Google', providerColor: '#4285f4', categories: ['Text Generation', 'Code', 'Chat', 'Open Source'], description: "Google's lightweight open-source model outperforming models twice its size, designed for responsible AI on consumer hardware.", contextWindow: 8192, pricing: { input: 0.0, unit: 'free (open weights)', tier: 'free' }, strengths: ['Open weights', 'Runs on consumer hardware'], limitations: ['Smaller context window'], scores: { reasoning: 74, coding: 73, creativity: 70, speed: 90, multimodal: 20, contextHandling: 45, costEfficiency: 100 }, releaseDate: '2024-06', openSource: true, apiAvailable: true },
  { slug: 'phi-3-mini', name: 'Phi-3 Mini', provider: 'Microsoft', providerColor: '#00a4ef', categories: ['Text Generation', 'Code', 'Open Source', 'Speed'], description: "Microsoft's 3.8B parameter open-source model outperforming models 10× its size on coding benchmarks. Ideal for edge/mobile.", contextWindow: 128000, pricing: { input: 0.0, unit: 'free (open weights)', tier: 'free' }, strengths: ['Edge/mobile deployment', 'Tiny footprint'], limitations: ['Less capable than large models'], scores: { reasoning: 70, coding: 76, creativity: 60, speed: 99, multimodal: 0, contextHandling: 85, costEfficiency: 100 }, releaseDate: '2024-04', openSource: true, apiAvailable: true },
  { slug: 'azure-gpt-4', name: 'Azure OpenAI GPT-4', provider: 'Microsoft', providerColor: '#00a4ef', categories: ['Text Generation', 'Enterprise', 'Code', 'Chat'], description: 'Enterprise-hosted GPT-4 with Azure compliance, private networking, and SLA options.', contextWindow: 128000, pricing: { input: 30.0, output: 60.0, unit: 'per 1M tokens', tier: 'premium' }, strengths: ['Enterprise compliance', 'VPC integration'], limitations: ['Higher list price', 'Azure account required'], scores: { reasoning: 93, coding: 90, creativity: 86, speed: 65, multimodal: 78, contextHandling: 88, costEfficiency: 40 }, releaseDate: '2024-01', openSource: false, apiAvailable: true },
  { slug: 'command-r-plus', name: 'Command R+', provider: 'Cohere', providerColor: '#39d353', categories: ['Text Generation', 'Reasoning', 'RAG', 'Enterprise'], description: "Cohere's enterprise model optimized for RAG, grounded responses, and complex business document workflows.", contextWindow: 128000, pricing: { input: 3.0, output: 15.0, unit: 'per 1M tokens', tier: 'mid' }, strengths: ['RAG-optimized architecture', 'Citation grounding'], limitations: ['Weaker creative writing'], scores: { reasoning: 83, coding: 78, creativity: 70, speed: 80, multimodal: 0, contextHandling: 88, costEfficiency: 72 }, releaseDate: '2024-04', openSource: false, apiAvailable: true },
  { slug: 'embed-english-v3', name: 'Embed English v3', provider: 'Cohere', providerColor: '#39d353', categories: ['Embeddings', 'RAG', 'Search'], description: 'High-quality text embeddings for semantic search, clustering, and retrieval pipelines.', contextWindow: 512, pricing: { input: 0.1, unit: 'per 1M tokens', tier: 'budget' }, strengths: ['Strong retrieval quality', 'Low cost'], limitations: ['Embeddings only'], scores: { reasoning: 0, coding: 0, creativity: 0, speed: 95, multimodal: 0, contextHandling: 40, costEfficiency: 98 }, releaseDate: '2023-11', openSource: false, apiAvailable: true },
  { slug: 'deepseek-v3', name: 'DeepSeek V3', provider: 'DeepSeek', providerColor: '#6366f1', categories: ['Text Generation', 'Code', 'Reasoning', 'Language'], description: 'Large MoE model with competitive coding and math benchmarks at aggressive API pricing.', contextWindow: 64000, pricing: { input: 0.27, output: 1.1, unit: 'per 1M tokens', tier: 'budget' }, strengths: ['Excellent price/performance', 'Strong code'], limitations: ['Newer ecosystem'], scores: { reasoning: 90, coding: 91, creativity: 80, speed: 82, multimodal: 35, contextHandling: 85, costEfficiency: 96 }, releaseDate: '2024-12', openSource: false, apiAvailable: true },
  { slug: 'deepseek-r1', name: 'DeepSeek R1', provider: 'DeepSeek', providerColor: '#6366f1', categories: ['Reasoning', 'Code', 'Research', 'Math'], description: 'Reasoning-first model with visible chain-of-thought style outputs for STEM workloads.', contextWindow: 64000, pricing: { input: 0.55, output: 2.19, unit: 'per 1M tokens', tier: 'mid' }, strengths: ['Math competitions', 'Long reasoning traces'], limitations: ['Latency on hardest prompts'], scores: { reasoning: 97, coding: 94, creativity: 78, speed: 68, multimodal: 30, contextHandling: 82, costEfficiency: 85 }, releaseDate: '2025-01', openSource: true, apiAvailable: true },
  { slug: 'qwen-2-5-72b', name: 'Qwen 2.5 72B', provider: 'Alibaba (Qwen)', providerColor: '#f97316', categories: ['Text Generation', 'Code', 'Multilingual', 'Open Source'], description: 'Open multilingual model with strong performance on coding and instruction following.', contextWindow: 131072, pricing: { input: 0.9, output: 0.9, unit: 'per 1M tokens (hosted)', tier: 'budget' }, strengths: ['Chinese + English', 'Open weights'], limitations: ['Heavy VRAM for self-host'], scores: { reasoning: 86, coding: 88, creativity: 78, speed: 75, multimodal: 45, contextHandling: 90, costEfficiency: 88 }, releaseDate: '2024-09', openSource: true, apiAvailable: true },
  { slug: 'grok-2', name: 'Grok 2', provider: 'xAI', providerColor: '#1f2937', categories: ['Text Generation', 'Chat', 'Reasoning', 'Real-time'], description: 'xAI model with real-time X data access and conversational personality.', contextWindow: 131072, pricing: { input: 5.0, output: 15.0, unit: 'per 1M tokens', tier: 'mid' }, strengths: ['Real-time data hooks', 'Strong chat'], limitations: ['Ecosystem lock-in'], scores: { reasoning: 88, coding: 84, creativity: 86, speed: 80, multimodal: 55, contextHandling: 85, costEfficiency: 62 }, releaseDate: '2024-08', openSource: false, apiAvailable: true },
  { slug: 'perplexity-sonar', name: 'Sonar Large', provider: 'Perplexity', providerColor: '#22c55e', categories: ['Search', 'Research', 'Text Generation', 'Reasoning'], description: 'Answer engine model with live web citations and concise summaries.', contextWindow: 127072, pricing: { input: 1.0, output: 1.0, unit: 'per 1M tokens', tier: 'budget' }, strengths: ['Citations', 'Fresh data'], limitations: ['Not for creative long-form'], scores: { reasoning: 82, coding: 72, creativity: 65, speed: 88, multimodal: 40, contextHandling: 80, costEfficiency: 90 }, releaseDate: '2024-06', openSource: false, apiAvailable: true },
  { slug: 'nova-pro', name: 'Amazon Nova Pro', provider: 'Amazon', providerColor: '#f59e0b', categories: ['Text Generation', 'Multimodal', 'Enterprise', 'Code'], description: 'AWS Bedrock multimodal model for document Q&A, image understanding, and enterprise agents.', contextWindow: 300000, pricing: { input: 0.8, output: 3.2, unit: 'per 1M tokens', tier: 'mid' }, strengths: ['Bedrock integration', 'IAM & VPC'], limitations: ['AWS-centric workflow'], scores: { reasoning: 85, coding: 82, creativity: 76, speed: 78, multimodal: 82, contextHandling: 92, costEfficiency: 78 }, releaseDate: '2024-12', openSource: false, apiAvailable: true },
  { slug: 'titan-text-v2', name: 'Titan Text G1', provider: 'Amazon', providerColor: '#f59e0b', categories: ['Text Generation', 'Enterprise', 'Chat'], description: 'Amazon Titan text model for enterprise knowledge bases and secure workloads on AWS.', contextWindow: 32000, pricing: { input: 0.5, output: 1.5, unit: 'per 1M tokens', tier: 'budget' }, strengths: ['AWS compliance', 'Simple API'], limitations: ['Not frontier-tier reasoning'], scores: { reasoning: 76, coding: 72, creativity: 68, speed: 85, multimodal: 0, contextHandling: 75, costEfficiency: 88 }, releaseDate: '2024-03', openSource: false, apiAvailable: true },
  { slug: 'bedrock-claude-3-5', name: 'Claude 3.5 Sonnet (Bedrock)', provider: 'Amazon', providerColor: '#f59e0b', categories: ['Text Generation', 'Code', 'Reasoning', 'Enterprise'], description: 'Anthropic Claude 3.5 Sonnet hosted on Amazon Bedrock with AWS-native governance.', contextWindow: 200000, pricing: { input: 3.0, output: 15.0, unit: 'per 1M tokens', tier: 'mid' }, strengths: ['Same Sonnet quality', 'Bedrock IAM'], limitations: ['AWS account required'], scores: { reasoning: 97, coding: 98, creativity: 90, speed: 78, multimodal: 75, contextHandling: 98, costEfficiency: 65 }, releaseDate: '2024-10', openSource: false, researchOnly: false, apiAvailable: true },
  { slug: 'grok-4', name: 'Grok 4', provider: 'xAI', providerColor: '#1f2937', categories: ['Text Generation', 'Reasoning', 'Language', 'Real-time'], description: 'Frontier xAI model with stronger reasoning, tool use, and live knowledge hooks for flagship workloads.', contextWindow: 256000, pricing: { input: 3.0, output: 12.0, unit: 'per 1M tokens', tier: 'premium' }, strengths: ['Flagship reasoning', 'Real-time signals'], limitations: ['Premium tier'], scores: { reasoning: 96, coding: 92, creativity: 90, speed: 82, multimodal: 70, contextHandling: 94, costEfficiency: 48 }, releaseDate: '2025-03', openSource: false, researchOnly: false, apiAvailable: true },
  { slug: 'ernie-4', name: 'ERNIE 4.0 Turbo', provider: 'Baidu', providerColor: '#2932e1', categories: ['Text Generation', 'Language', 'Chat', 'Reasoning'], description: 'Baidu flagship Chinese–English model with strong long-document and enterprise compliance features.', contextWindow: 8192, pricing: { input: 0.4, output: 1.2, unit: 'per 1M tokens', tier: 'budget' }, strengths: ['Chinese fluency', 'Enterprise SLAs'], limitations: ['Smaller ecosystem outside CN'], scores: { reasoning: 84, coding: 78, creativity: 76, speed: 86, multimodal: 45, contextHandling: 80, costEfficiency: 90 }, releaseDate: '2024-08', openSource: false, researchOnly: false, apiAvailable: true },
  { slug: 'mt5-xxl-nmt', name: 'mT5-XXL NMT', provider: 'Google', providerColor: '#4285f4', categories: ['Language', 'Translation', 'Text Generation'], description: 'Massively multilingual Tuned model for translation, transliteration, and low-resource language pairs.', contextWindow: 1024, pricing: { input: 0.2, output: 0.2, unit: 'per 1M tokens', tier: 'budget' }, strengths: ['100+ languages', 'Low cost'], limitations: ['Narrow context'], scores: { reasoning: 65, coding: 55, creativity: 60, speed: 88, multimodal: 0, contextHandling: 40, costEfficiency: 96 }, releaseDate: '2023-01', openSource: true, researchOnly: false, apiAvailable: true },
  { slug: 'nllb-200', name: 'NLLB-200', provider: 'Meta', providerColor: '#0668e1', categories: ['Language', 'Translation', 'Open Source'], description: 'Open dense model covering 200 languages — ideal for humanitarian and research translation at scale.', contextWindow: 512, pricing: { input: 0.0, unit: 'free (open weights)', tier: 'free' }, strengths: ['200 languages', 'Open weights'], limitations: ['Legacy architecture'], scores: { reasoning: 55, coding: 40, creativity: 45, speed: 75, multimodal: 0, contextHandling: 35, costEfficiency: 100 }, releaseDate: '2022-07', openSource: true, researchOnly: false, apiAvailable: true },
  { slug: 'aqua-translate-pro', name: 'Aqua Translate Pro', provider: 'Cohere', providerColor: '#39d353', categories: ['Language', 'Enterprise', 'Text Generation'], description: 'Enterprise translation and localisation stack with glossary, tone, and brand-voice controls.', contextWindow: 128000, pricing: { input: 1.5, output: 1.5, unit: 'per 1M tokens', tier: 'mid' }, strengths: ['Glossary control', 'Audit logs'], limitations: ['Translation-focused'], scores: { reasoning: 72, coding: 60, creativity: 65, speed: 85, multimodal: 0, contextHandling: 82, costEfficiency: 78 }, releaseDate: '2024-05', openSource: false, researchOnly: false, apiAvailable: true },
  { slug: 'lingua-7b', name: 'Lingua 7B', provider: 'Mistral AI', providerColor: '#ff6b35', categories: ['Language', 'Chat', 'Text Generation'], description: 'Compact multilingual chat model optimised for EU languages and low-latency edge deployment.', contextWindow: 32768, pricing: { input: 0.1, output: 0.1, unit: 'per 1M tokens', tier: 'budget' }, strengths: ['Fast', 'EU hosting'], limitations: ['Not frontier reasoning'], scores: { reasoning: 74, coding: 70, creativity: 68, speed: 94, multimodal: 0, contextHandling: 78, costEfficiency: 95 }, releaseDate: '2024-09', openSource: false, researchOnly: false, apiAvailable: true },
  { slug: 'polyglot-ultra', name: 'Polyglot Ultra', provider: 'Anthropic', providerColor: '#d4794a', categories: ['Language', 'Reasoning', 'Analysis', 'Chat'], description: 'Instruction-tuned for nuanced translation, dialect handling, and cross-lingual summarisation.', contextWindow: 200000, pricing: { input: 4.0, output: 16.0, unit: 'per 1M tokens', tier: 'mid' }, strengths: ['Dialect nuance', 'Long context'], limitations: ['Higher cost'], scores: { reasoning: 90, coding: 78, creativity: 82, speed: 76, multimodal: 50, contextHandling: 96, costEfficiency: 62 }, releaseDate: '2024-11', openSource: false, researchOnly: false, apiAvailable: true },
  { slug: 'babel-mini', name: 'Babel Mini', provider: 'OpenAI', providerColor: '#10a37f', categories: ['Language', 'Speed', 'Chat'], description: 'Lightweight model for real-time chat translation in 50+ languages with sub-200ms latency.', contextWindow: 8000, pricing: { input: 0.08, output: 0.24, unit: 'per 1M tokens', tier: 'budget' }, strengths: ['Ultra low latency', 'Cheap'], limitations: ['Not for complex reasoning'], scores: { reasoning: 62, coding: 58, creativity: 55, speed: 98, multimodal: 0, contextHandling: 55, costEfficiency: 98 }, releaseDate: '2024-10', openSource: false, researchOnly: false, apiAvailable: true },
  { slug: 'sanskrit-bert-research', name: 'Indic Research BERT', provider: 'Google', providerColor: '#4285f4', categories: ['Language', 'Research'], description: 'Non-commercial research checkpoint for classical Indic languages and low-resource NLP benchmarks.', contextWindow: 512, pricing: { input: 0.0, unit: 'free (academic)', tier: 'free' }, strengths: ['Classical languages', 'Benchmark leader'], limitations: ['Research-only licence'], scores: { reasoning: 58, coding: 40, creativity: 45, speed: 70, multimodal: 0, contextHandling: 30, costEfficiency: 100 }, releaseDate: '2023-05', openSource: true, researchOnly: true, apiAvailable: false },
  { slug: 'llama-research-70b', name: 'Llama 3.1 70B (Research)', provider: 'Meta', providerColor: '#0668e1', categories: ['Research', 'Language', 'Code'], description: 'Research-only weight release for academic reproducibility — not for production commercial use.', contextWindow: 128000, pricing: { input: 0.0, unit: 'free (academic licence)', tier: 'free' }, strengths: ['Reproducibility', 'Open weights'], limitations: ['Academic licence only'], scores: { reasoning: 78, coding: 80, creativity: 72, speed: 72, multimodal: 0, contextHandling: 82, costEfficiency: 100 }, releaseDate: '2024-07', openSource: true, researchOnly: true, apiAvailable: false },
  { slug: 'gpt-4o-language-edition', name: 'GPT-4o Language Edition', provider: 'OpenAI', providerColor: '#10a37f', categories: ['Language', 'Text Generation', 'Chat', 'Translation'], description: 'Variant tuned for translation, glossaries, and bilingual workflows with improved idiom handling.', contextWindow: 128000, pricing: { input: 3.0, output: 12.0, unit: 'per 1M tokens', tier: 'mid' }, strengths: ['Idiom handling', 'Glossary'], limitations: ['Higher cost than base 4o-mini'], scores: { reasoning: 92, coding: 82, creativity: 86, speed: 84, multimodal: 70, contextHandling: 90, costEfficiency: 68 }, releaseDate: '2024-08', openSource: false, researchOnly: false, apiAvailable: true },
  { slug: 'atlas-general-1', name: 'Atlas General 1', provider: 'Anthropic', providerColor: '#d4794a', categories: ['Text Generation', 'Chat', 'Reasoning', 'Language'], description: 'General-purpose Atlas tier for broad discovery — balanced cost and capability across everyday tasks.', contextWindow: 200000, pricing: { input: 2.5, output: 10.0, unit: 'per 1M tokens', tier: 'mid' }, strengths: ['Balanced', 'Long context'], limitations: ['Not specialised'], scores: { reasoning: 88, coding: 85, creativity: 82, speed: 80, multimodal: 65, contextHandling: 94, costEfficiency: 72 }, releaseDate: '2024-06', openSource: false, researchOnly: false, apiAvailable: true },
  { slug: 'frontier-all-1', name: 'Frontier One', provider: 'OpenAI', providerColor: '#10a37f', categories: ['Text Generation', 'Multimodal', 'Code', 'Chat'], description: 'Omnibus flagship for “All” workloads — routing, agents, and mixed modality in one endpoint.', contextWindow: 256000, pricing: { input: 8.0, output: 24.0, unit: 'per 1M tokens', tier: 'premium' }, strengths: ['Versatile', 'Agent routing'], limitations: ['Premium pricing'], scores: { reasoning: 94, coding: 92, creativity: 90, speed: 78, multimodal: 92, contextHandling: 96, costEfficiency: 42 }, releaseDate: '2025-01', openSource: false, researchOnly: false, apiAvailable: true },
];

async function seed() {
  try {
    await mongoose.connect(MONGO_URI);
    console.log('Connected to MongoDB');
    await AIModel.deleteMany({});
    console.log('Cleared existing models');
    await AIModel.insertMany(models);
    console.log(`Seeded ${models.length} AI models`);
    await mongoose.disconnect();
    console.log('Done.');
  } catch (err) {
    console.error('Seed error:', err.message);
    process.exit(1);
  }
}

seed();
